# commit_allure_reports.yml
name: Commit Allure Reports

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: false

jobs:
  commit_allure_reports:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v2
      - name: Add private key and pre-commit steps
        if: ${{ github.actor != 'github-actions[bot]' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          git remote -v
          git remote set-url origin git@github.com:hpillai-akamai/pytest-allure-github-actions.git
          git config --global user.email "hpillai@akamai.com"
          git config --global user.name "hpillai-akamai"

          sudo apt install allure
          wget https://github.com/allure-framework/allure2/releases/download/2.15.0/allure-2.15.0.zip
          unzip allure-2.15.0.zip
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
          allure generate allure-results/allure-results-cases -o allure-report-1 

      - name: Import artifacts from test run
        uses: actions/download-artifact@v2
        with:
          name: allure-results-zip
          path: allure-results.zip

      - name: Unzip allure-results.zip
        run: |
          pwd
          ls
          unzip allure-results.zip

      - name: Commit Allure Reports
        run: |
          cp -r allure-report-1/history/. allure-results/allure-results-cases/history/.
          cp -r allure-report-1/. docs/allure-report-cases/.
          allure generate allure-results/allure-results-calculator -o allure-report-2
          cp -r allure-report-2/history/. allure-results/allure-results-calculator/history/.
          cp -r allure-report-calculator/. docs/allure-report-calculator/.
          # git add allure-report-cases
          # git add allure-report-calculator
          git pull
          git add allure-results
          git add docs
          git commit -m "Add Allure reports"
          git push origin main
