# commit_allure_reports.yml
name: Commit Allure Reports

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  commit-allure-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          if ! command -v ssh-agent > /dev/null; then
            sudo apt-get update -y
            sudo apt-get install openssh-client wget gnupg -y
          fi

      - name: Install Docker GPG Key
        run: |
          curl -fsSL https://get.docker.com/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

      - name: Set up Docker repository
        run: |
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Start SSH Agent
        run: eval $(ssh-agent -s)
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Add SSH Private Key
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-add ~/.ssh/id_ed25519

      - name: Set up SSH Configuration
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          chmod -R 400 ~/.ssh
          '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

      - name: Install Docker
        run: |
          sudo apt-get update -y
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y

      - name: Commit Allure Reports
        if: ${{ github.actor != 'github-actions[bot]' }}
        run: |
          git remote -v
          git remote set-url origin git@github.com:hpillai-akamai/pytest-allure-github-actions.git
          git config --global user.email "hpillai@akamai.com"
          git config --global user.name "hpillai-akamai"
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
          allure generate allure-results/allure-results-calculator -o allure-report-2
          cp -r allure-report-2/history/. allure-results/allure-results-calculator/history/.
          cp -r allure-report-2/. docs/allure-report-calculator/.
          git pull
          git add allure-results
          git add docs
          git commit -m "Add Allure reports"
          git push origin main
