name: Trigger Workflows on Schedule

on:
  schedule:
    - cron: "*/6 * * * *"
    - cron: "*/10 * * * *"

jobs:
  trigger-wf-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger wf-cases.yml workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/wf-cases.yml/dispatches
          echo "Workflow wf-cases.yml triggered."

  trigger-wf-calculator:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger wf-calculator.yml workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/wf-calculator.yml/dispatches
          echo "Workflow wf-calculator.yml triggered."
