name: Trigger Workflows on Schedule

on:
  schedule:
    - cron: '*/6 * * * *'
    - cron: '*/10 * * * *'

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger wf-cases
        uses: 'actions/actions-runner-controller@v3'
        with:
          runner_group: workflow-trigger
          workflow_file: wf-cases.yaml

      - name: Trigger wf-calculator
        uses: 'actions/actions-runner-controller@v3'
        with:
          runner_group: workflow-trigger
          workflow_file: wf-calculator.yaml
