name: Run component tests for calculator and show reports

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: '5 * * * *'
  push:
    paths-ignore:
      - 'allure-results/**'
      - 'allure-report-**'
      - 'docs/**'

jobs:
  trigger_component_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggering user is GitHub Actions bot
        run: echo "Is GitHub Actions bot? ${{ github.actor == 'github-actions[bot]' }}" >> /dev/null

  install_and_run_tests:
    needs: trigger_component_tests
    runs-on: ubuntu-latest
    # steps:
    uses: ./.github/workflows/install_and_run_tests.yml

  commit_allure_reports:
    needs: install_and_run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/commit_allure_reports.yml

  publish_to_pages:
    needs: commit_allure_reports
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/publish_to_pages.yml

  show_allure_report:
    needs: publish_to_pages
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/show_allure_report.yml

  archive_allure_artifact:
    needs: show_allure_report
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/archive_allure_artifact.yml
