name: Trigger Workflows on Schedule

on:
  schedule:
    - cron: '*/6 * * * *'
    - cron: '*/10 * * * *'

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger wf-cases
        run: |
          gh workflow run wf-cases.yaml -R hpillai-akamai/pytest-allure-github-actions

      - name: Trigger wf-calculator
        run: |
          gh workflow run wf-calculator.yaml -R hpillai-akamai/pytest-allure-github-actions
