name: Run component tests for calculator and show reports

on:
  schedule:
    - cron: '5 * * * *'
  push:
    paths-ignore:
      - 'allure-results/**'
      - 'allure-report-**'
      - 'docs/**'

jobs:
  trigger_component_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggering user is GitHub Actions bot
        id: check_bot
        run: echo "Is GitHub Actions bot? ${{ github.actor == 'github-actions[bot]' }}" >> /dev/null
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: ./.github/workflows/install_and_run_tests.yml
      - name: Check if triggering user is GitHub Actions bot
        id: check_bot
        run: echo "Is GitHub Actions bot? ${{ github.actor == 'github-actions[bot]' }}" >> /dev/null
      - uses: ./.github/workflows/commit_allure_reports.yml


      - uses: ./.github/workflows/publish_to_pages.yml


      - uses: ./.github/workflows/show_allure_report.yml


      - uses: ./.github/workflows/archive_allure_artifact.yml
