name: Trigger Workflows on Schedule

on:
  schedule:
    - cron: '*/6 * * * *'
    - cron: '*/10 * * * *'

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger wf-cases
        uses: actions/workflow-dispatch@v2
        with:
          workflow_file: wf-cases.yaml

      - name: Trigger wf-calculator
        uses: actions/workflow-dispatch@v2
        with:
          workflow_file: wf-calculator.yaml
