name: Build Docker Image

on:
  workflow_call:
    inputs:
      tagname:
        description: 'Name of tag'
        required: true
        type: string
      dockerfile:
        description: 'Path to the Dockerfile'
        required: true
        type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      #      - name: Set up Docker Build
      #        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.tagname }} .
      - name: Docker run
        env:
          AUTH_KEY_FILE: ${{ secrets.AUTH_KEY}}
        run: |
          ls