# install_and_run_tests.yml
name: Install Allure and Run Tests

on:
  workflow_call:
    inputs:
      data-folder:
        required: false
        type: string
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false
        
jobs:
  install_and_run_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Allure command-line tool and Run test_calculator.py
        continue-on-error: true
        run: |
          git pull
          sudo apt install allure
          wget https://github.com/allure-framework/allure2/releases/download/2.15.0/allure-2.15.0.zip
          unzip allure-2.15.0.zip
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
          allure --version
          pytest test_calculator.py -v -p no:warnings --alluredir=./allure-results/allure-results-calculator

      - name: Zip allure result run
        continue-on-error: true
        run: |
          ls allure-2.15.0/bin
          ls allure-results
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
          allure generate allure-results -o allure-report
          
      - name: Upload Data as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: 'allure-report'
          
      - name: Commit Allure Reports
        if: ${{ github.actor != 'github-actions[bot]' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          pwd
          ls
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          git remote -v
          git remote set-url origin git@github.com:hpillai-akamai/pytest-allure-github-actions.git
          git config --global user.email "hpillai@akamai.com"
          git config --global user.name "hpillai-akamai"
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
          # allure generate allure-results/allure-results-cases -o allure-report-1 
          # cp -r allure-report-1/history/. allure-results/allure-results-cases/history/.
          # cp -r allure-report-1/. docs/allure-report-cases/.
          allure generate allure-results/allure-results-calculator -o allure-report-2
          cp -r allure-report-2/history/. allure-results/allure-results-calculator/history/.
          cp -r allure-report-2/. docs/allure-report-calculator/.
          # git add allure-report-cases
          # git add allure-report-calculator
          git add allure-results
          git add docs
          git commit -m "Add Allure reports"
          git push origin main

      - name: publish to github pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: allure-report
          token: ${{ secrets.MY_GITHUB_TOKEN }}