# publish_to_pages.yml
name: Publish to GitHub Pages

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  publish-to-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Pages test_calculator
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'workflow_run'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./allure-report-calculator
          cname: hpillai-akamai.github.io
