name: Run component tests for calculator and show reports

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'allure-results/**'
      - 'allure-report-**'
      - 'docs/**'
  pull_request:
    branches:
      - main

jobs:
  component-tests-calculator:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggering user is GitHub Actions bot
        id: check_bot
        run: echo "Is GitHub Actions bot? ${{ github.actor == 'github-actions[bot]' }}" >> /dev/null

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Use Encrypted Secret
        id: get-secrets
        run: |
          export GIT_SECRETS_DATA=$(secret.SECRET_1)
          echo "GIT_SECRETS_DATA=$GIT_SECRETS_DATA"

      - name: Use git secrets data
        run: |
          export SECRET_VAR="${{ secrets.SECRET_1 }}"
          echo "$SECRET_VAR"
          echo "The git secrets data is: ${{ secrets.SECRET_1 }}"

      - name: Install Allure command-line tool and Run test_calculator.py
        continue-on-error: true
        run: |
          sudo apt install allure
          wget https://github.com/allure-framework/allure2/releases/download/2.15.0/allure-2.15.0.zip
          unzip allure-2.15.0.zip
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
          allure --version
          pytest test_calculator.py -v -p no:warnings --alluredir=./allure-results/allure-results-calculator


      - name: Commit Allure Reports
        if: ${{ github.actor != 'github-actions[bot]' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          git remote -v
          git remote set-url origin git@github.com:hpillai-akamai/pytest-allure-github-actions.git
          git config --global user.email "hpillai@akamai.com"
          git config --global user.name "hpillai-akamai"
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
          allure generate allure-results/allure-results-calculator -o allure-report-2
          cp -r allure-report-2/history/. allure-results/allure-results-calculator/history/.
          cp -r allure-report-calculator/. docs/allure-report-calculator/.
          git pull
          git add allure-results
          git add docs
          git commit -m "Add Allure reports"
          git push origin main

      - name: Pull Repository Changes
        run: git pull origin main





      - name: Publish to GitHub Pages test_calculator
        if: github.event_name == 'push'  
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./allure-report-calculator
          cname: hpillai-akamai.github.io 

      - name: Show allure report
        continue-on-error: true
        run: |
          ls allure-2.15.0/bin
          ls allure-results
          zip -r allure-reports.zip allure-results

      - name: Archive Allure zip artifact
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: allure-reports-zip
          path: allure-reports.zip 
